# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertiesDialog.ui'
#
# Created: Fri May 10 15:57:36 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_propertiesDialog(object):
    def setupUi(self, propertiesDialog):
        propertiesDialog.setObjectName(_fromUtf8("propertiesDialog"))
        propertiesDialog.resize(624, 457)
        propertiesDialog.setMinimumSize(QtCore.QSize(624, 457))
        propertiesDialog.setMaximumSize(QtCore.QSize(624, 457))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/tokens.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        propertiesDialog.setWindowIcon(icon)
        self.formLayout = QtGui.QFormLayout(propertiesDialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.frame = QtGui.QFrame(propertiesDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.basicButton = QtGui.QToolButton(self.frame)
        self.basicButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicButton.sizePolicy().hasHeightForWidth())
        self.basicButton.setSizePolicy(sizePolicy)
        self.basicButton.setMinimumSize(QtCore.QSize(80, 80))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.basicButton.setIcon(icon1)
        self.basicButton.setIconSize(QtCore.QSize(32, 32))
        self.basicButton.setCheckable(True)
        self.basicButton.setAutoExclusive(True)
        self.basicButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.basicButton.setObjectName(_fromUtf8("basicButton"))
        self.gridLayout.addWidget(self.basicButton, 0, 0, 1, 1)
        self.offenseButton = QtGui.QToolButton(self.frame)
        self.offenseButton.setMinimumSize(QtCore.QSize(80, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/swords.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offenseButton.setIcon(icon2)
        self.offenseButton.setIconSize(QtCore.QSize(32, 32))
        self.offenseButton.setCheckable(True)
        self.offenseButton.setAutoExclusive(True)
        self.offenseButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.offenseButton.setObjectName(_fromUtf8("offenseButton"))
        self.gridLayout.addWidget(self.offenseButton, 0, 1, 1, 1)
        self.defenseButton = QtGui.QToolButton(self.frame)
        self.defenseButton.setMinimumSize(QtCore.QSize(80, 80))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/shield.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defenseButton.setIcon(icon3)
        self.defenseButton.setIconSize(QtCore.QSize(32, 32))
        self.defenseButton.setCheckable(True)
        self.defenseButton.setAutoExclusive(True)
        self.defenseButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.defenseButton.setObjectName(_fromUtf8("defenseButton"))
        self.gridLayout.addWidget(self.defenseButton, 0, 2, 1, 1)
        self.miscButton = QtGui.QToolButton(self.frame)
        self.miscButton.setMinimumSize(QtCore.QSize(80, 80))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.miscButton.setIcon(icon4)
        self.miscButton.setIconSize(QtCore.QSize(32, 32))
        self.miscButton.setCheckable(True)
        self.miscButton.setAutoExclusive(True)
        self.miscButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.miscButton.setObjectName(_fromUtf8("miscButton"))
        self.gridLayout.addWidget(self.miscButton, 0, 3, 1, 1)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.frame)
        self.stackedWidget = QtGui.QStackedWidget(propertiesDialog)
        self.stackedWidget.setMinimumSize(QtCore.QSize(500, 300))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageBasic = QtGui.QWidget()
        self.pageBasic.setObjectName(_fromUtf8("pageBasic"))
        self.line = QtGui.QFrame(self.pageBasic)
        self.line.setGeometry(QtCore.QRect(40, 100, 551, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.pageBasic)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelPlayer = QtGui.QLabel(self.layoutWidget)
        self.labelPlayer.setMinimumSize(QtCore.QSize(0, 0))
        self.labelPlayer.setObjectName(_fromUtf8("labelPlayer"))
        self.gridLayout_2.addWidget(self.labelPlayer, 0, 0, 1, 1)
        self.editPlayer = QtGui.QLineEdit(self.layoutWidget)
        self.editPlayer.setObjectName(_fromUtf8("editPlayer"))
        self.gridLayout_2.addWidget(self.editPlayer, 0, 1, 1, 2)
        self.labelRace = QtGui.QLabel(self.layoutWidget)
        self.labelRace.setObjectName(_fromUtf8("labelRace"))
        self.gridLayout_2.addWidget(self.labelRace, 0, 3, 1, 1)
        self.editRace = QtGui.QLineEdit(self.layoutWidget)
        self.editRace.setObjectName(_fromUtf8("editRace"))
        self.gridLayout_2.addWidget(self.editRace, 0, 4, 1, 1)
        self.labelAlignment = QtGui.QLabel(self.layoutWidget)
        self.labelAlignment.setMinimumSize(QtCore.QSize(80, 0))
        self.labelAlignment.setObjectName(_fromUtf8("labelAlignment"))
        self.gridLayout_2.addWidget(self.labelAlignment, 1, 0, 1, 2)
        self.editAlignment = QtGui.QLineEdit(self.layoutWidget)
        self.editAlignment.setObjectName(_fromUtf8("editAlignment"))
        self.gridLayout_2.addWidget(self.editAlignment, 1, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.pageBasic)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 150, 591, 131))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelStr = QtGui.QLabel(self.layoutWidget1)
        self.labelStr.setObjectName(_fromUtf8("labelStr"))
        self.gridLayout_3.addWidget(self.labelStr, 0, 0, 1, 1)
        self.editStr = QtGui.QLineEdit(self.layoutWidget1)
        self.editStr.setObjectName(_fromUtf8("editStr"))
        self.gridLayout_3.addWidget(self.editStr, 0, 1, 1, 2)
        self.labelInt = QtGui.QLabel(self.layoutWidget1)
        self.labelInt.setObjectName(_fromUtf8("labelInt"))
        self.gridLayout_3.addWidget(self.labelInt, 0, 3, 1, 3)
        self.editInt = QtGui.QLineEdit(self.layoutWidget1)
        self.editInt.setObjectName(_fromUtf8("editInt"))
        self.gridLayout_3.addWidget(self.editInt, 0, 6, 1, 1)
        self.labelDex = QtGui.QLabel(self.layoutWidget1)
        self.labelDex.setObjectName(_fromUtf8("labelDex"))
        self.gridLayout_3.addWidget(self.labelDex, 1, 0, 1, 1)
        self.editDex = QtGui.QLineEdit(self.layoutWidget1)
        self.editDex.setObjectName(_fromUtf8("editDex"))
        self.gridLayout_3.addWidget(self.editDex, 1, 1, 1, 2)
        self.labelWis = QtGui.QLabel(self.layoutWidget1)
        self.labelWis.setObjectName(_fromUtf8("labelWis"))
        self.gridLayout_3.addWidget(self.labelWis, 1, 3, 1, 1)
        self.editWis = QtGui.QLineEdit(self.layoutWidget1)
        self.editWis.setObjectName(_fromUtf8("editWis"))
        self.gridLayout_3.addWidget(self.editWis, 1, 4, 1, 3)
        self.labelCon = QtGui.QLabel(self.layoutWidget1)
        self.labelCon.setObjectName(_fromUtf8("labelCon"))
        self.gridLayout_3.addWidget(self.labelCon, 2, 0, 1, 2)
        self.editCon = QtGui.QLineEdit(self.layoutWidget1)
        self.editCon.setObjectName(_fromUtf8("editCon"))
        self.gridLayout_3.addWidget(self.editCon, 2, 2, 1, 1)
        self.labelCha = QtGui.QLabel(self.layoutWidget1)
        self.labelCha.setObjectName(_fromUtf8("labelCha"))
        self.gridLayout_3.addWidget(self.labelCha, 2, 3, 1, 2)
        self.editCha = QtGui.QLineEdit(self.layoutWidget1)
        self.editCha.setObjectName(_fromUtf8("editCha"))
        self.gridLayout_3.addWidget(self.editCha, 2, 5, 1, 2)
        self.stackedWidget.addWidget(self.pageBasic)
        self.pageOffense = QtGui.QWidget()
        self.pageOffense.setObjectName(_fromUtf8("pageOffense"))
        self.editMelee = QtGui.QLineEdit(self.pageOffense)
        self.editMelee.setGeometry(QtCore.QRect(120, 50, 148, 27))
        self.editMelee.setObjectName(_fromUtf8("editMelee"))
        self.labelMelee = QtGui.QLabel(self.pageOffense)
        self.labelMelee.setGeometry(QtCore.QRect(24, 50, 90, 27))
        self.labelMelee.setObjectName(_fromUtf8("labelMelee"))
        self.editBAB = QtGui.QLineEdit(self.pageOffense)
        self.editBAB.setGeometry(QtCore.QRect(360, 60, 208, 27))
        self.editBAB.setObjectName(_fromUtf8("editBAB"))
        self.labelBAB = QtGui.QLabel(self.pageOffense)
        self.labelBAB.setGeometry(QtCore.QRect(324, 60, 30, 27))
        self.labelBAB.setObjectName(_fromUtf8("labelBAB"))
        self.labelRanged = QtGui.QLabel(self.pageOffense)
        self.labelRanged.setGeometry(QtCore.QRect(25, 89, 99, 30))
        self.labelRanged.setObjectName(_fromUtf8("labelRanged"))
        self.editRanged = QtGui.QLineEdit(self.pageOffense)
        self.editRanged.setGeometry(QtCore.QRect(130, 90, 137, 27))
        self.editRanged.setObjectName(_fromUtf8("editRanged"))
        self.labelCMB = QtGui.QLabel(self.pageOffense)
        self.labelCMB.setGeometry(QtCore.QRect(321, 99, 33, 30))
        self.labelCMB.setObjectName(_fromUtf8("labelCMB"))
        self.editCMB = QtGui.QLineEdit(self.pageOffense)
        self.editCMB.setGeometry(QtCore.QRect(360, 100, 203, 27))
        self.editCMB.setObjectName(_fromUtf8("editCMB"))
        self.stackedWidget.addWidget(self.pageOffense)
        self.pageDefense = QtGui.QWidget()
        self.pageDefense.setObjectName(_fromUtf8("pageDefense"))
        self.labelCMD = QtGui.QLabel(self.pageDefense)
        self.labelCMD.setGeometry(QtCore.QRect(30, 130, 34, 30))
        self.labelCMD.setObjectName(_fromUtf8("labelCMD"))
        self.editCMD = QtGui.QLineEdit(self.pageDefense)
        self.editCMD.setGeometry(QtCore.QRect(70, 131, 202, 27))
        self.editCMD.setObjectName(_fromUtf8("editCMD"))
        self.labelCMDFlat = QtGui.QLabel(self.pageDefense)
        self.labelCMDFlat.setGeometry(QtCore.QRect(300, 130, 107, 31))
        self.labelCMDFlat.setObjectName(_fromUtf8("labelCMDFlat"))
        self.editCMDFlat = QtGui.QLineEdit(self.pageDefense)
        self.editCMDFlat.setGeometry(QtCore.QRect(413, 132, 129, 27))
        self.editCMDFlat.setObjectName(_fromUtf8("editCMDFlat"))
        self.editAC = QtGui.QLineEdit(self.pageDefense)
        self.editAC.setGeometry(QtCore.QRect(100, 20, 165, 27))
        self.editAC.setObjectName(_fromUtf8("editAC"))
        self.labelAC = QtGui.QLabel(self.pageDefense)
        self.labelAC.setGeometry(QtCore.QRect(21, 20, 73, 27))
        self.labelAC.setObjectName(_fromUtf8("labelAC"))
        self.labelACFlat = QtGui.QLabel(self.pageDefense)
        self.labelACFlat.setGeometry(QtCore.QRect(300, 20, 94, 27))
        self.labelACFlat.setObjectName(_fromUtf8("labelACFlat"))
        self.editACFlat = QtGui.QLineEdit(self.pageDefense)
        self.editACFlat.setGeometry(QtCore.QRect(400, 20, 144, 27))
        self.editACFlat.setObjectName(_fromUtf8("editACFlat"))
        self.labelACTouch = QtGui.QLabel(self.pageDefense)
        self.labelACTouch.setGeometry(QtCore.QRect(21, 50, 63, 27))
        self.labelACTouch.setObjectName(_fromUtf8("labelACTouch"))
        self.editACTouch = QtGui.QLineEdit(self.pageDefense)
        self.editACTouch.setGeometry(QtCore.QRect(90, 50, 175, 27))
        self.editACTouch.setObjectName(_fromUtf8("editACTouch"))
        self.line_2 = QtGui.QFrame(self.pageDefense)
        self.line_2.setGeometry(QtCore.QRect(40, 100, 551, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.stackedWidget.addWidget(self.pageDefense)
        self.pageMisc = QtGui.QWidget()
        self.pageMisc.setObjectName(_fromUtf8("pageMisc"))
        self.lineEdit_12 = QtGui.QLineEdit(self.pageMisc)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 30, 161, 27))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_12 = QtGui.QLabel(self.pageMisc)
        self.label_12.setGeometry(QtCore.QRect(19, 29, 75, 30))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_13 = QtGui.QLineEdit(self.pageMisc)
        self.lineEdit_13.setGeometry(QtCore.QRect(368, 31, 184, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_13 = QtGui.QLabel(self.pageMisc)
        self.label_13.setGeometry(QtCore.QRect(310, 30, 52, 30))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.pageMisc)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 90, 194, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_14 = QtGui.QLabel(self.pageMisc)
        self.label_14.setGeometry(QtCore.QRect(32, 89, 42, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.pageMisc)
        self.lineEdit_15.setGeometry(QtCore.QRect(360, 90, 194, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_15 = QtGui.QLabel(self.pageMisc)
        self.label_15.setGeometry(QtCore.QRect(312, 89, 42, 30))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.stackedWidget.addWidget(self.pageMisc)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(propertiesDialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(propertiesDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), propertiesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), propertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(propertiesDialog)
        propertiesDialog.setTabOrder(self.editPlayer, self.editRace)
        propertiesDialog.setTabOrder(self.editRace, self.editAlignment)
        propertiesDialog.setTabOrder(self.editAlignment, self.editStr)
        propertiesDialog.setTabOrder(self.editStr, self.editInt)
        propertiesDialog.setTabOrder(self.editInt, self.editDex)
        propertiesDialog.setTabOrder(self.editDex, self.editWis)
        propertiesDialog.setTabOrder(self.editWis, self.editCon)
        propertiesDialog.setTabOrder(self.editCon, self.editCha)
        propertiesDialog.setTabOrder(self.editCha, self.editMelee)
        propertiesDialog.setTabOrder(self.editMelee, self.editBAB)
        propertiesDialog.setTabOrder(self.editBAB, self.editRanged)
        propertiesDialog.setTabOrder(self.editRanged, self.editCMB)
        propertiesDialog.setTabOrder(self.editCMB, self.editAC)
        propertiesDialog.setTabOrder(self.editAC, self.editACFlat)
        propertiesDialog.setTabOrder(self.editACFlat, self.editACTouch)
        propertiesDialog.setTabOrder(self.editACTouch, self.editCMD)
        propertiesDialog.setTabOrder(self.editCMD, self.editCMDFlat)
        propertiesDialog.setTabOrder(self.editCMDFlat, self.lineEdit_12)
        propertiesDialog.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        propertiesDialog.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        propertiesDialog.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        propertiesDialog.setTabOrder(self.lineEdit_15, self.defenseButton)
        propertiesDialog.setTabOrder(self.defenseButton, self.buttonBox)
        propertiesDialog.setTabOrder(self.buttonBox, self.basicButton)
        propertiesDialog.setTabOrder(self.basicButton, self.offenseButton)
        propertiesDialog.setTabOrder(self.offenseButton, self.miscButton)

    def retranslateUi(self, propertiesDialog):
        propertiesDialog.setWindowTitle(QtGui.QApplication.translate("propertiesDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.basicButton.setText(QtGui.QApplication.translate("propertiesDialog", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.offenseButton.setText(QtGui.QApplication.translate("propertiesDialog", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        self.defenseButton.setText(QtGui.QApplication.translate("propertiesDialog", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        self.miscButton.setText(QtGui.QApplication.translate("propertiesDialog", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPlayer.setText(QtGui.QApplication.translate("propertiesDialog", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRace.setText(QtGui.QApplication.translate("propertiesDialog", "Race", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAlignment.setText(QtGui.QApplication.translate("propertiesDialog", "Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStr.setText(QtGui.QApplication.translate("propertiesDialog", "Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInt.setText(QtGui.QApplication.translate("propertiesDialog", "Intelligence", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDex.setText(QtGui.QApplication.translate("propertiesDialog", "Dexterity", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWis.setText(QtGui.QApplication.translate("propertiesDialog", "Wisdom", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCon.setText(QtGui.QApplication.translate("propertiesDialog", "Constitution", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCha.setText(QtGui.QApplication.translate("propertiesDialog", "Charisma", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMelee.setText(QtGui.QApplication.translate("propertiesDialog", "Melee Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBAB.setText(QtGui.QApplication.translate("propertiesDialog", "BAB", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRanged.setText(QtGui.QApplication.translate("propertiesDialog", "Ranged Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCMB.setText(QtGui.QApplication.translate("propertiesDialog", "CMB", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCMD.setText(QtGui.QApplication.translate("propertiesDialog", "CMD", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCMDFlat.setText(QtGui.QApplication.translate("propertiesDialog", "CMD Flatfooted", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAC.setText(QtGui.QApplication.translate("propertiesDialog", "AC Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.labelACFlat.setText(QtGui.QApplication.translate("propertiesDialog", "AC Flatfooted", None, QtGui.QApplication.UnicodeUTF8))
        self.labelACTouch.setText(QtGui.QApplication.translate("propertiesDialog", "AC Touch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("propertiesDialog", "HP Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("propertiesDialog", "HP Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("propertiesDialog", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("propertiesDialog", "Reach", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
